export const TRADERS = [
  {
    id: 1,
    name: "Marcus Webb",
    handle: "marcuswebb",
    badge: "Elite",
    strategy: "ORB Momentum",
    instruments: ["NQ", "ES"],
    score: 94,
    color: "#00E5A0",
    metrics: {
      profitFactor: 3.21,
      winRate: 67,
      maxDrawdown: 4.2,
      sharpe: 2.8,
      avgRR: 2.4,
      consistency: 91,
      monthsVerified: 18,
      totalTrades: 847,
      monthlyReturn: 8.4,
    },
  },
  {
    id: 2,
    name: "Priya Nair",
    handle: "priyanair_fx",
    badge: "Pro",
    strategy: "Supply & Demand",
    instruments: ["GBP/USD", "EUR/USD"],
    score: 89,
    color: "#a78bfa",
    metrics: {
      profitFactor: 2.74,
      winRate: 58,
      maxDrawdown: 6.1,
      sharpe: 2.3,
      avgRR: 3.1,
      consistency: 86,
      monthsVerified: 12,
      totalTrades: 412,
      monthlyReturn: 6.1,
    },
  },
  {
    id: 3,
    name: "Deon Fourie",
    handle: "deonfourie",
    badge: "Elite",
    strategy: "Mean Reversion",
    instruments: ["MNQ", "Gold"],
    score: 87,
    color: "#00E5A0",
    metrics: {
      profitFactor: 2.98,
      winRate: 72,
      maxDrawdown: 3.8,
      sharpe: 2.1,
      avgRR: 1.8,
      consistency: 88,
      monthsVerified: 24,
      totalTrades: 1203,
      monthlyReturn: 5.7,
    },
  },
  {
    id: 4,
    name: "Aisha Kamara",
    handle: "aishafutures",
    badge: "Rising",
    strategy: "Breakout + Momentum",
    instruments: ["BTC", "ETH"],
    score: 81,
    color: "#fbbf24",
    metrics: {
      profitFactor: 2.12,
      winRate: 54,
      maxDrawdown: 8.4,
      sharpe: 1.9,
      avgRR: 2.7,
      consistency: 79,
      monthsVerified: 6,
      totalTrades: 231,
      monthlyReturn: 9.2,
    },
  },
  {
    id: 5,
    name: "James Thorn",
    handle: "thorntrading",
    badge: "Pro",
    strategy: "Order Flow",
    instruments: ["ES", "CL"],
    score: 78,
    color: "#a78bfa",
    metrics: {
      profitFactor: 1.87,
      winRate: 61,
      maxDrawdown: 9.2,
      sharpe: 1.7,
      avgRR: 2.1,
      consistency: 74,
      monthsVerified: 9,
      totalTrades: 388,
      monthlyReturn: 4.8,
    },
  },
] as const;

export const COMMUNITIES = [
  {
    id: 1,
    name: "Byond Capital Club",
    handle: "byondcapital",
    badge: "Featured",
    platform: "Whop + Discord",
    focus: "Futures",
    score: 96,
    verified: true,
    color: "#00E5A0",
    pricing: "$149/mo",
    metrics: {
      avgPF: 2.4,
      memberWinRate: 63,
      verifiedTraders: 47,
      retention: 91,
      activeMembers: 892,
      totalMembers: 1100,
      avgConsistency: 84,
      avgMemberGrowth: 12.4,
    },
  },
  {
    id: 2,
    name: "Precision FX Labs",
    handle: "precisionfx",
    badge: "Top Rated",
    platform: "Discord",
    focus: "Forex",
    score: 91,
    verified: true,
    color: "#a78bfa",
    pricing: "$99/mo",
    metrics: {
      avgPF: 2.1,
      memberWinRate: 58,
      verifiedTraders: 31,
      retention: 87,
      activeMembers: 640,
      totalMembers: 780,
      avgConsistency: 81,
      avgMemberGrowth: 9.8,
    },
  },
  {
    id: 3,
    name: "The Prop Desk",
    handle: "thepropdeskk",
    badge: "Pro",
    platform: "Skool",
    focus: "Prop Firms",
    score: 85,
    verified: true,
    color: "#fbbf24",
    pricing: "$79/mo",
    metrics: {
      avgPF: 1.9,
      memberWinRate: 55,
      verifiedTraders: 22,
      retention: 82,
      activeMembers: 430,
      totalMembers: 520,
      avgConsistency: 77,
      avgMemberGrowth: 7.2,
    },
  },
  {
    id: 4,
    name: "Alpha Scalpers",
    handle: "alphascalpers",
    badge: "Unverified",
    platform: "Telegram",
    focus: "Crypto Signals",
    score: 42,
    verified: false,
    color: "#ef4444",
    pricing: "$299/mo",
    metrics: {
      avgPF: 0.9,
      memberWinRate: 41,
      verifiedTraders: 2,
      retention: 51,
      activeMembers: 4200,
      totalMembers: 8100,
      avgConsistency: 38,
      avgMemberGrowth: -2.1,
    },
  },
] as const;

export const MOCK_TRADERS = TRADERS;

